In [1]:
grid=[[0,0,2,0,8,0,0,6,0],
     [0,5,6,9,1,7,0,3,0],
     [0,4,0,0,5,0,8,7,1],
     [0,9,0,0,0,0,6,0,0],
     [6,7,1,0,9,5,2,0,0],
     [0,0,0,0,2,0,1,0,0],
     [1,6,7,0,3,0,5,9,0],
     [4,8,0,0,7,0,3,0,0],
     [0,2,5,4,6,0,0,0,0]]

In [2]:
print(grid)

[[0, 0, 2, 0, 8, 0, 0, 6, 0], [0, 5, 6, 9, 1, 7, 0, 3, 0], [0, 4, 0, 0, 5, 0, 8, 7, 1], [0, 9, 0, 0, 0, 0, 6, 0, 0], [6, 7, 1, 0, 9, 5, 2, 0, 0], [0, 0, 0, 0, 2, 0, 1, 0, 0], [1, 6, 7, 0, 3, 0, 5, 9, 0], [4, 8, 0, 0, 7, 0, 3, 0, 0], [0, 2, 5, 4, 6, 0, 0, 0, 0]]


In [3]:
import numpy as np
print(np.matrix(grid))

[[0 0 2 0 8 0 0 6 0]
 [0 5 6 9 1 7 0 3 0]
 [0 4 0 0 5 0 8 7 1]
 [0 9 0 0 0 0 6 0 0]
 [6 7 1 0 9 5 2 0 0]
 [0 0 0 0 2 0 1 0 0]
 [1 6 7 0 3 0 5 9 0]
 [4 8 0 0 7 0 3 0 0]
 [0 2 5 4 6 0 0 0 0]]


In [4]:
def possible(y,x,n):
    global grid
    for i in range(0,9):
        if grid[y][i] ==n:
            return False
    for i in range(0,9):
        if grid[i][x] ==n:
            return False
    
    
    x0=(x//3)*3
    y0=(y//3)*3
    
    for i in range(0,3):
        for j in range(0,3):
            if grid[y0+i][x0+j] ==n:
                return False
            
    return True
            

In [5]:
possible(4,4,3)

False

In [6]:
possible(4,4,5)

False

In [7]:
def solve():
    global grid
    for y in range(9):
        for x in range(9):
            if grid[y][x]==0:
                for n in range(1,10):
                    if possible(y,x,n):
                        grid[y][x]=n
                        solve()
                        grid[y][x]=0
                return
    print(np.matrix(grid))
    input("More?")

In [8]:
solve()

[[7 1 2 3 8 4 9 6 5]
 [8 5 6 9 1 7 4 3 2]
 [9 4 3 6 5 2 8 7 1]
 [2 9 8 1 4 3 6 5 7]
 [6 7 1 8 9 5 2 4 3]
 [5 3 4 7 2 6 1 8 9]
 [1 6 7 2 3 8 5 9 4]
 [4 8 9 5 7 1 3 2 6]
 [3 2 5 4 6 9 7 1 8]]
More?0


In [9]:
grid=[[5,3,0,0,7,0,0,0,0],
     [6,0,0,1,9,5,0,0,0],
     [0,9,8,0,0,0,0,6,0],
     [8,0,0,0,6,0,0,0,3],
     [4,0,0,8,0,3,0,0,1],
     [7,0,0,0,2,0,0,0,6],
     [0,6,0,0,0,0,2,8,0],
     [0,0,0,4,1,9,0,0,5],
     [0,0,0,0,8,0,0,7,9]]

In [10]:
solve()

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
More?0


In [11]:
grid=[[0,0,4,7,1,0,0,0,0,],
     [0,7,2,8,0,6,5,0,0,],
     [0,0,0,0,0,5,0,0,7],
     [0,1,0,6,9,0,2,0,0],
     [3,9,0,0,5,0,0,0,0],
     [0,0,0,0,0,0,0,8,5],
     [0,0,1,2,3,0,8,0,4],
     [0,0,3,5,0,4,0,0,2],
     [2,4,0,9,0,0,0,0,0]]

In [13]:
solve()

[[5 3 4 7 1 9 6 2 8]
 [1 7 2 8 4 6 5 3 9]
 [8 6 9 3 2 5 4 1 7]
 [7 1 5 6 9 8 2 4 3]
 [3 9 8 4 5 2 7 6 1]
 [4 2 6 1 7 3 9 8 5]
 [6 5 1 2 3 7 8 9 4]
 [9 8 3 5 6 4 1 7 2]
 [2 4 7 9 8 1 3 5 6]]
More?0
